### ISSUE TITLE
Having problems understanding the results.

### ISSUE THREAD

**Issue by sinanlag** [pokanop/nostromo#34] opened 2021-03-13 09:35 UTC
1) nostromo add cmd mp '/usr/bin/mpv'  is ok; cmd alias is added/created
2) nostromo add cmd mp.nr '--no-resume-playback'  --- this fails with msg: 
      "error: unknown flag: --no-resume-playback"
3) nostromo add cmd mpnr 'mpv --no-resume-playback'  --- this succeeds
4) nostromo add cmd mpnrp '/usr/bin/mpv --no-resume-playback' -- this fails as 2) above

nostromo doesn't like specifying the full path names of commands? But why should 1) above succeed? why should 2) above fail.

**Comment by saheljalal** [comment] 2021-03-13 10:06
Hi @sinanlag, thanks for providing the feedback. A few things I noticed in trying to repro the issues:

I'm able to run the command in 4. without any issues, so not sure what's going on with that.

It appears there might be a bug in how you're trying to concatenate the commands together using `add cmd`. I was able to replicate the command you are trying to achieve by this workaround and manually editing the `manifest.yaml`:
```sh
❯ nostromo add cmd mp '/usr/local/bin/mpv'
keypath: mp alias: mp command: /usr/local/bin/mpv
❯ nostromo add cmd mp.nr 'foo --no-resume-playback'
keypath: mp.nr alias: nr command: foo --no-resume-playback
// edit ~/nostromo.yaml and remove "foo " prefix
❯ mp nr
key path: mp.nr
executing: /usr/local/bin/mpv --no-resume-playback
```

There may be some error in positional args being mistaken for `nostromo` flags instead of being part of the command itself. Will keep this open and look into trying to root cause when I can make some time 🙂

Hope the workaround helps in the meantime.

**Comment by sinanlag** [comment] 2021-03-15 00:56
saheljalal,

Thx for responding to my email.

s

**Comment by saheljalal** [comment] 2022-01-16 09:09
Sorry for the delayed update but some more notes on this. In your second command, this works by using the `--` operator since the shell doesn't know if this is a positional argument or option. This works as expected:
```sh
nostromo add cmd mp.nr -- --no-resume-playback 
keypath: mp.nr alias: nr command: --no-resume-playback 
```

Closing this for now as there are workarounds to construct the commands as expected.

**Closed by saheljalal** 2022-01-16 09:09 UTC
Labels: bug
